mysql:
 image: mysql:5.7.15
 environment:
   MYSQL_ROOT_PASSWORD: root
 ports:
   - 3306:3306
 volumes:
   - ./DB_Scripts.sql:/docker-entrypoint-initdb.d/DB_Scripts.sql
   - ./sql:/var/lib/mysql

webapp:
 build: ./
 ports:
  - 8888:8080
 links:
   - mysql
